### ISSUE TITLE
Obligation de se connecter avec un compte barman/chef de bar pour decompter des consos hors de l'ordi du bar

### ISSUE THREAD

**Issue by robinshin** [Babaritech/babar3#8]
Des gens non barmen pourraient s'amuser à décompter des consos.
Du coup, ca serait bien d'etre obligé d'entrer des identifiants valides pour accéder au site mis à part l'ordi du bar

**Comment by dryvenn** [comment]
I'm aware of this problem and I'm glad you brought it up. Unfortunately, it's trickier than it sounds. So I'm gonna try to explain where we're at and we can see where to go from there.

First of all, I must say I'm not fond of your idea of granting more privileges to a given computer. The way I see it, it boils down to hardcoding a specific IP, and this is just bad.

Now, let's sum up what's going on in babar3's authentication scheme. Whenever a privileged operation is attempted (for example a POST to /payment) without providing some credentials, a 401 error is returned. The client then performs a login using Basic Authentication (which is settting the "Authorization" header to "Basic <username>:<password>") and gets back a token on success. It then tries again the operation that was refused using Token Authentication (which is setting the "Authorization" header to "Token <token>") and if the user associated to the token has sufficient permission, the operation is a success.
As of now, tokens are only valid for a one-time use, meaning that the client can ditch it immediately after having used it once.

What was done before in the previous version of babar was a permanent Basic Authentication scheme. Accessing the website required valid username and password. And this wasn't enforced by the babar server itself, but by Apache (think of it as a secure interface between the babar server and the outside world). The consequence was that the "Authorization" header was filled with Basic credentials by the browser (ie Firefox) and not by the javascript program as it is the case in the above paragraph.

So now, you can very well figure out that if both the browser and the javascript software try to fill the same "Authorization" header, there is conflict and it won't work.

> Make the browser use a different header!

To my knowledge, it's impossible (because it is a standard).

> Make the babar server use a different header!

The babar server uses [Django REST Framework](http://www.django-rest-framework.org/), and you can't change the header either (still a standard).

> Make Apache change the header before transmitting the request to the babar server!

This is feasible, and I've tried it. "Authorization" was filled by the browser, "X-User-Authorization" by the javascript program.
Only as I said earlier, there are sometimes 401 errors fired (at every restricted operation actually). And when that happens, the browser detects it and forgets the credentials, requiring to login once again.


##### Let's resume:
The way I see it, there are two solutions:
- Generate long-life tokens for usual operations like purchases, and stack atop short-life tokens for more sensible operations like payments. This is kinda over-engineering the thing.
- Make the client smarter so that 401 are never fired.

As I'm fairly new to this kind of issues, I'm open to suggestions. @Iansus , @davinov , do you guys have any?

**Comment by dryvenn** [comment]
![03085543-87de-47ab-a4eb-58e7e39d022e-620x372](https://cloud.githubusercontent.com/assets/6233736/14527337/69667a78-0249-11e6-8cba-b495ab0e4db3.jpeg)

**Comment by dryvenn** [comment]
Fixed in 45c28dc and 2e8f2c3.
